<?php
/**
 * Ajax routine to Store Device id token generated from Google's FireBase
 * based on user subscription from browser to allow push notifications.
 *
 * @param string   $_POST['device_id'] Device id sent from firebase ajax routine
 * @param string   $_POST['subscriptionoptions'] Push notification subscription code using Firebase as push notification provider
 * @param string   $_POST['onesignal_subscriptionoptions'] Push notification subscription code using Onesignal as push notification provider
 * @param string   $_POST['pushtype'] Push notification call types using Firebase/Onesignal push notification
 * @param string   $_POST['onesignal_externalid'] Onesignal push notification external id
 * @param string   $_POST['pnfpb_endpoint'] Push notification Subscription endpoint
 * @param string   $_POST['pnfpb_options'] Push notification subscription vapid key
 *
 *
 * @since 1.0.0
 */
require __DIR__ . '/../../vendor/autoload.php';
$bpdeviceid = '';
if (isset($_POST['device_id'])) {
    /** Sanitize the device id generated by Google's Firebase for the user who subscribed push notification  **/
    $bpdeviceid = sanitize_text_field($_POST['device_id']);
}
$bpsubscribeoptions = '10000000000';
if (isset($_POST['subscriptionoptions'])) {
    $bpsubscribeoptions = sanitize_text_field($_POST['subscriptionoptions']);
    $bpsubscribeoptions = esc_html($bpsubscribeoptions);
}
if (isset($_POST['onesignal_subscriptionoptions'])) {
    $bpsubscribeoptions = sanitize_text_field($_POST['onesignal_subscriptionoptions']);
    $bpsubscribeoptions = esc_html($bpsubscribeoptions);
}
if ($bpsubscribeoptions === '' || $bpsubscribeoptions === '10000') {
    $bpsubscribeoptions = '10000000000';
}
$bponesignalid = 0;
if (isset($_POST['onesignal_get_subscriptionoptions_id'])) {
    $bponesignalid = sanitize_text_field($_POST['onesignal_get_subscriptionoptions_id']);
    $bponesignalid = esc_html($bponesignalid);
    if ($bponesignalid === '1pnfpbadm') {
        $bponesignalid = 1;
    }
    if ($bponesignalid === null || ($bponesignalid !== null && !is_numeric($bponesignalid)) || $bponesignalid === '') {
        $bponesignalid = 0;
    }
}
if (isset($_POST['progressier_subscriptionoptions'])) {
    $bpsubscribeoptions = sanitize_text_field($_POST['progressier_subscriptionoptions']);
    $bpsubscribeoptions = esc_html($bpsubscribeoptions);
    if ($bpsubscribeoptions === '' || $bpsubscribeoptions === '10000') {
        $bpsubscribeoptions = '10000000000';
    }
}
$bpprogressierid = 0;
if (isset($_POST['progressier_get_subscriptionoptions_id'])) {
    $bpprogressierid = sanitize_text_field($_POST['progressier_get_subscriptionoptions_id']);
    $bpprogressierid = esc_html($bpprogressierid);
    if ($bpprogressierid === null || ($bpprogressierid !== null && !is_numeric($bpprogressierid)) || $bpprogressierid === '') {
        $bpprogressierid = 0;
    }
}

$bpwebtoappid = 0;
if (isset($_POST['webtoapp_userid'])) {
    $bpwebtoappid = sanitize_text_field($_POST['webtoapp_userid']);
    $bpwebtoappid = esc_html($bpwebtoappid);
    if ($bpwebtoappid === null || ($bpwebtoappid !== null && !is_numeric($bpwebtoappid)) || $bpwebtoappid === '') {
        $bpwebtoappid = 0;
    }
}

$bpwebtoapp_deviceid = '';
if (isset($_POST['webtoapp_deviceid'])) {
    $bpwebtoapp_deviceid = sanitize_text_field($_POST['webtoapp_deviceid']);
    $bpwebtoapp_deviceid = esc_html($bpwebtoapp_deviceid);
}
/** securing data from Firebase who subscribed push notification  **/
$bpdeviceid = esc_html($bpdeviceid);
$pushtype = 'normal';
$pnfpbshortcodeactive = 'no';
global $wpdb;
$table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
$dbname = $wpdb->dbname;
if (isset($_POST['pushtype'])) {
    $pushtype = sanitize_text_field($_POST['pushtype']);
    $pushtype = esc_html($pushtype);
}
$isadminpage = 'no';
if (isset($_POST['pnfpbshortcodeactive'])) {
    if (isset($_POST['isadminpage'])) {
        $isadminpage = $_POST['isadminpage'];
    }
    $pnfpbshortcodeactive = sanitize_text_field($_POST['pnfpbshortcodeactive']);
    $pnfpbshortcodeactive = esc_html($pnfpbshortcodeactive);
    if ($isadminpage === 'no') {
        update_option('pnfpb_shortcode_enable', $pnfpbshortcodeactive);
    }
}
$pnfpb_endpoint = null;
$pnfpb_options = null;
$pnfpb_ipaddress = null;
if (isset($_POST['pnfpb_endpoint'])) {
    $pnfpb_endpoint = sanitize_text_field($_POST['pnfpb_endpoint']);
}
if (isset($_POST['pnfpb_options'])) {
    $pnfpb_options = sanitize_text_field($_POST['pnfpb_options']);
}
if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $pnfpb_ipaddress = $_SERVER['HTTP_CLIENT_IP'];
}
//whether ip is from the proxy
elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $pnfpb_ipaddress = $_SERVER['HTTP_X_FORWARDED_FOR'];
}
//whether ip is from the remote address
else {
    $pnfpb_ipaddress = $_SERVER['REMOTE_ADDR'];
}
$bpuserid = 0;
if (is_user_logged_in()) {
    $bpuserid = get_current_user_id();
}
/*********************************************************************************************
 * To send Firebase credentials to Javascript to process push notification
 *
 **********************************************************************************************/
if ($pushtype == 'icfirebasecred') {
    echo json_encode(array('apiKey' => get_option('pnfpb_ic_fcm_api'), 'authDomain' => get_option('pnfpb_ic_fcm_authdomain'), 'databaseURL' => get_option('pnfpb_ic_fcm_databaseurl'), 'projectId' => get_option('pnfpb_ic_fcm_projectid'), 'storageBucket' => get_option('pnfpb_ic_fcm_storagebucket'), 'messagingSenderId' => get_option('pnfpb_ic_fcm_messagingsenderid'), 'appId' => get_option('pnfpb_ic_fcm_appid'), 'publicKey' => get_option('pnfpb_ic_fcm_publickey')));
}

/*********************************************************************************************
* Update webtoapp subscribed user id and device id in WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
 if ($pushtype === 'webtoapp_subscribed_users') {
	 
        $results = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE userid = %d AND device_id LIKE %s", array($bpwebtoappid, '%' . $wpdb->esc_like($bpwebtoapp_deviceid) . '%')));
        if (count($results) <= 0) {
            $data = array('userid' => $bpwebtoappid, 'device_id' => $bpwebtoapp_deviceid, 'subscription_option' => '100000000000', 'ip_address' => $pnfpb_ipaddress);
            $insertstatus = $wpdb->insert($table, $data);
            if (!$insertstatus) {
                echo json_encode(array('subscriptionstatus' => 'error', 'message' => $insertstatus));
            } else {
                echo json_encode(array('subscriptionstatus' => 'subscribed', 'message' => $bpwebtoapp_deviceid));
            }
        } else {
            foreach ($results as $result) {
                if ($result->subscription_option === null || $result->subscription_option === '') {
                    $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE userid = %d", array($bpsubscribeoptions, $bpwebtoappid)));
                }
            }
            echo json_encode(array('subscriptionstatus' => 'subscribed', 'message' => $result->device_id));
        }	 
	 
 }
/*********************************************************************************************
 * Update Progressier subscribed user external id in WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
if ($pushtype === 'progressier_subscribed_users') {
    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $dbname = $wpdb->dbname;
    if (isset($_POST['progressier_external_id'])) {
        $progressier_externalid = sanitize_text_field($_POST['progressier_external_id']);
        $progressier_externalid = esc_html($progressier_externalid);
        if ($progressier_externalid === null || ($progressier_externalid !== null && !is_numeric($progressier_externalid)) || $progressier_externalid === '') {
            $progressier_externalid = 0;
        }
        $results = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE userid = %d AND device_id LIKE %s", array($progressier_externalid, '%' . $wpdb->esc_like('progressier') . '%')));
        if (count($results) <= 0) {
            $length = 10;
            $progressier_deviceid = substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'), 1, $length) . 'progressier@N';
            $data = array('userid' => $progressier_externalid, 'device_id' => $progressier_deviceid, 'subscription_option' => '100000000000', 'ip_address' => $pnfpb_ipaddress);
            $insertstatus = $wpdb->insert($table, $data);
            if (!$insertstatus) {
                echo json_encode(array('subscriptionstatus' => 'error', 'message' => $insertstatus));
            } else {
                echo json_encode(array('subscriptionstatus' => 'subscribed', 'message' => $progressier_deviceid));
            }
        } else {
            foreach ($results as $result) {
                if ($result->subscription_option === null || $result->subscription_option === '') {
                    $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE userid = %d", array($bpsubscribeoptions, $progressier_externalid)));
                }
            }
            echo json_encode(array('subscriptionstatus' => 'subscribed', 'message' => $result->device_id));
        }
    }
}
/*********************************************************************************************
 * Update Onesignal subscribed user external id in WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
if ($pushtype == 'onesignal_subscribed_users') {
    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $dbname = $wpdb->dbname;
    if (isset($_POST['onesignal_externalid'])) {
        $onesignal_externalid = sanitize_text_field($_POST['onesignal_externalid']);
        $onesignal_externalid = esc_html($onesignal_externalid);
        if ($onesignal_externalid === '1pnfpbadm') {
            $onesignal_externalid = 1;
        }
        if ($onesignal_externalid === null || ($onesignal_externalid !== null && !is_numeric($onesignal_externalid)) || $onesignal_externalid === '') {
            $onesignal_externalid = 0;
        }
        $results = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE userid = %d AND device_id LIKE %s", array($onesignal_externalid, '%' . $wpdb->esc_like('onesignal') . '%')));
        if (count($results) <= 0) {
            $data = array('userid' => $onesignal_externalid, 'device_id' => 'onesignal@N', 'subscription_option' => '100000000000', 'ip_address' => $pnfpb_ipaddress);
            $insertstatus = $wpdb->insert($table, $data);
            if (!$insertstatus) {
                echo "error in inserting onesignal subscription details in PNFPB for id: " . $onesignal_externalid;
            } else {
                echo '';
            }
        } else {
            foreach ($results as $result) {
                if ($result->subscription_option === null || $result->subscription_option === '') {
                    $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE userid = %d", array($bpsubscribeoptions, $onesignal_externalid)));
                }
            }
        }
    }
}
/*********************************************************************************************
 * Get User's Onesignal Frontend subscription code from WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
if ($pushtype == 'onesignal_get_frontend_subscriptions') {
    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $dbname = $wpdb->dbname;
    $data = '';
    if ($bponesignalid !== 0) {
        $results = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE userid = %d AND device_id LIKE %s", array($bponesignalid, '%' . $wpdb->esc_like('onesignal') . '%')));
        foreach ($results as $result) {
            $data = array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $result->subscription_option);
        }
        echo json_encode($data);
    } else {
        echo json_encode(array('subscriptionstatus' => 'notsubscribed', 'subscriptionoptions' => ''));
    }
}
/*********************************************************************************************
 * Update Onesignal Frontend subscription code in WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
if ($pushtype == 'onesignal_frontend_subscriptions') {
    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $dbname = $wpdb->dbname;
    if ($bpuserid !== 0) {
        $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE userid = %d", array($bpsubscribeoptions, $bpuserid)));
    }
    echo json_encode(array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $bpsubscribeoptions));
}
/*********************************************************************************************
 * Get User's Progressier Frontend subscription code from WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
if ($pushtype == 'progressier_get_frontend_subscriptions') {
    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $dbname = $wpdb->dbname;
    $data = '';
    if ($bpprogressierid !== 0) {
        $results = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE userid = %d AND device_id LIKE %s", array($bpprogressierid, '%' . $wpdb->esc_like('progressier') . '%')));
        foreach ($results as $result) {
            $data = array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $result->subscription_option);
        }
        echo json_encode($data);
    } else {
        echo json_encode(array('subscriptionstatus' => 'notsubscribed', 'subscriptionoptions' => ''));
    }
}
/*********************************************************************************************
 * Update Progressier Frontend subscription code in WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
if ($pushtype == 'progressier_frontend_subscriptions') {
    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $dbname = $wpdb->dbname;
    if ($bpuserid !== 0) {
        $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE userid = %d", array($bpsubscribeoptions, $bpuserid)));
    }
    echo json_encode(array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $bpsubscribeoptions));
}
/*********************************************************************************************
 * Add New user's Firebase subscription details in WordPress PNFPB plugin table
 * pnfpb_ic_subscribed_deviceids_web
 **********************************************************************************************/
if ($bpdeviceid != '' && $pushtype == 'normal') {
    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $dbname = $wpdb->dbname;
    $deviceid_exists = $wpdb->get_results($wpdb->prepare("SELECT * FROM $table WHERE device_id LIKE %s ", array('%' . $wpdb->esc_like($bpdeviceid) . '%')));
    foreach ($deviceid_exists as $result) {
        if ($result->userid == 0 || $result->userid != $bpuserid) {
            $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET userid = %d WHERE device_id = %s", $bpuserid, $bpdeviceid));
        }
        if (is_null($result->web_auth)) {
            $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET web_auth = %s, web_256 = %s, ip_address = %s WHERE device_id = %s", $pnfpb_endpoint, $pnfpb_options, $pnfpb_ipaddress, $bpdeviceid));
        }
    }
    if (count($deviceid_exists) > 0) {
        $results = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE device_id = %d AND (device_id NOT LIKE %s OR device_id LIKE %s)", $bpdeviceid, '%' . $wpdb->esc_like('!!') . '%', '%' . $wpdb->esc_like('webview') . '%'));
        $version_value = 'L';
        foreach ($results as $result) {
            $version_value = $result->firebase_version;
        }
        /*********************************************************************************************
         * Automate Migrate user's subscription token from Legacy Firebase to latest
         * Firebase httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
         **********************************************************************************************/
        if (($version_value !== 'httpv3' && $version_value !== 'httpv4') && get_option('pnfpb_httpv1_push') === '1') {
            $client = new Google_Client();
            // Authentication with the GOOGLE_APPLICATION_CREDENTIALS environment variable
            $client->useApplicationDefaultCredentials();
            // Alternatively, provide the JSON authentication file directly.
            $configArray = json_decode(get_option('pnfpb_sa_json_data'), true);
            $client->setAuthConfig($configArray);
            // Add the scope as a string (multiple scopes can be provided as an array)
            $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
            $client->refreshTokenWithAssertion();
            $pnfpb_fbauth_token_array = $client->getAccessToken();
            $pnfpb_fbauth_token = $pnfpb_fbauth_token_array['access_token'];
            $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
            $headers = array('Authorization' => 'Bearer ' . $pnfpb_fbauth_token, 'Content-Type' => 'application/json', 'access_token_auth' => 'true');
            if (get_option('pnfpb_ic_fcm_loggedin_notify') && get_option('pnfpb_ic_fcm_loggedin_notify') === '1') {
                $fields = array("to" => "/topics/pnfpbgeneralloggedin", "registration_tokens" => array($bpdeviceid));
            } else {
                $fields = array("to" => "/topics/pnfpbgeneral", "registration_tokens" => array($bpdeviceid));
            }
            $body = json_encode($fields);
            $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
            $apiresults = wp_remote_post($url, $args);
            $deviceid_version_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET firebase_version = %s WHERE device_id = %s", 'httpv4', $bpdeviceid));
        }
        $results = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE firebase_version != %s AND device_id = %s AND (device_id LIKE %s OR device_id NOT LIKE %s)", 'httpv2', $bpdeviceid, '%' . $wpdb->esc_like('!!') . '%', '%' . $wpdb->esc_like('webview') . '%'));
        $version_value = 'L';
        foreach ($results as $result) {
            $version_value = $result->firebase_version;
            $device_id = $result->device_id;
            $device_id_array = explode("!!", $device_id);
            if (count($device_id_array) > 1) {
                $group_id = $device_id_array[1];
                $topics = '/topics/pnfpbgroupid' . $bpgroupid;
                /*********************************************************************************************
                 * Automate Migrate user's subscription token from Legacy Firebase to latest
                 * Firebase httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                 **********************************************************************************************/
                if (($version_value !== 'httpv3' && $version_value !== 'httpv4') && get_option('pnfpb_httpv1_push') === '1') {
                    $client = new Google_Client();
                    // Authentication with the GOOGLE_APPLICATION_CREDENTIALS environment variable
                    $client->useApplicationDefaultCredentials();
                    // Alternatively, provide the JSON authentication file directly.
                    $configArray = json_decode(get_option('pnfpb_sa_json_data'), true);
                    $client->setAuthConfig($configArray);
                    // Add the scope as a string (multiple scopes can be provided as an array)
                    $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
                    $client->refreshTokenWithAssertion();
                    $pnfpb_fbauth_token_array = $client->getAccessToken();
                    $pnfpb_fbauth_token = $pnfpb_fbauth_token_array['access_token'];
                    $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
                    $headers = array('Authorization' => 'Bearer ' . $pnfpb_fbauth_token, 'Content-Type' => 'application/json', 'access_token_auth' => 'true');
                    $fields = array("to" => $topics, "registration_tokens" => array($bpdeviceid));
                    $body = json_encode($fields);
                    $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
                    $apiresults = wp_remote_post($url, $args);
                    $deviceid_version_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET firebase_version = %s WHERE device_id = %s", 'httpv3', $bpdeviceid));
                }
            }
        }
        echo "duplicate";
    } else {
        $data = array('userid' => $bpuserid, 'device_id' => $bpdeviceid, 'subscription_option' => $bpsubscribeoptions, 'web_auth' => $pnfpb_endpoint, 'web_256' => $pnfpb_options, 'ip_address' => $pnfpb_ipaddress, 'firebase_version' => 'httpv4');
        $insertstatus = $wpdb->insert($table, $data);
        if (!$insertstatus || $insertstatus != 0) {
            $my_id = $wpdb->insert_id;
            echo json_encode(array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $bpsubscribeoptions));
        } else {
            echo json_encode(array('subscriptionstatus' => 'fail', 'subscriptionoptions' => $bpsubscribeoptions));
        }
        /*********************************************************************************************
         * Automate Migrate user's subscription token from Legacy Firebase to latest
         * Firebase httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
         **********************************************************************************************/
		
         $subscription_option_array = array();
		
         if ($bpsubscribeoptions != '') {
             $subscription_option_array = str_split($bpsubscribeoptions);
          }
				
          if (get_option('pnfpb_httpv1_push') === '1' && $bpsubscribeoptions !== '' && (count($subscription_option_array) > 0 && $subscription_option_array[0] !== '1')) {
				PNFPB_httpv1_subscription_option_update($bpsubscribeoptions,$bpdeviceid);
          }

          if (get_option('pnfpb_httpv1_push') === '1' && (count($subscription_option_array) <= 0 || (count($subscription_option_array) > 0 && $subscription_option_array[0] === '1'))) {
				PNFPB_httpv1_default_subscription_option_update($bpdeviceid);
           }
    }
} else {
    /*********************************************************************************************
     * Add user's Firebase subscription details from Frontend subscription button in WordPress
     * PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
     **********************************************************************************************/
    if ($pushtype == 'subscribe-button') {
        $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
        $dbname = $wpdb->dbname;
		$old_subscription_option = '';
		$old_subscription_option_values = $wpdb->get_col($wpdb->prepare("SELECT subscription_option FROM {$table} WHERE device_id LIKE %s", '%' . $wpdb->esc_like($bpdeviceid) . '%'));
        foreach ($old_subscription_option_values as $old_subscription_option_value) {
            $old_subscription_option = $old_subscription_option_value;
         }		
		
        if ($bpdeviceid !== '') {			
            if ($bpuserid !== 0) {
                $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE userid = %d", $bpsubscribeoptions, $bpuserid));
                $deviceid_group_update_status = $deviceid_update_status;
            } else {
                $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE device_id LIKE %s AND device_id NOT LIKE %s", $bpsubscribeoptions, $bpdeviceid, '%' . $wpdb->esc_like('!!') . '%'));
                $deviceid_group_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE device_id LIKE %s AND device_id LIKE %s", $bpsubscribeoptions, $bpdeviceid, '%' . $wpdb->esc_like('!!') . '%'));
            }
            $deviceid_select_status = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE device_id LIKE %s", '%' . $wpdb->esc_like($bpdeviceid) . '%'));
            if ($deviceid_update_status > 0) {
                $version_values = $wpdb->get_col($wpdb->prepare("SELECT firebase_version FROM {$table} WHERE device_id LIKE %s", '%' . $wpdb->esc_like($bpdeviceid) . '%'));
                $version_value = 'L';
                foreach ($version_values as $value) {
                    $version_value = $value;
                }
                /*********************************************************************************************
                 * Automate Migrate user's subscription token from Legacy Firebase to latest
                 * Firebase httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                 **********************************************************************************************/
                $subscription_option_array = array();
                if ($bpsubscribeoptions != '') {
                    $subscription_option_array = str_split($bpsubscribeoptions);
                }
				
                if (get_option('pnfpb_httpv1_push') === '1' && $bpsubscribeoptions !== '') {
					PNFPB_httpv1_subscription_option_update($bpsubscribeoptions,$bpdeviceid,'',$old_subscription_option);
                }

                if (($version_value !== 'httpv3' && $version_value !== 'httpv4') && get_option('pnfpb_httpv1_push') === '1' && (count($subscription_option_array) <= 0 || (count($subscription_option_array) > 0 && $subscription_option_array[0] === '1'))) {
					PNFPB_httpv1_default_subscription_option_update($bpdeviceid);
                }
                echo json_encode(array('subscriptionstatus' => 'subscribed updated', 'subscriptionoptions' => $bpsubscribeoptions));
            } else {
                if ($deviceid_select_status != null && count($deviceid_select_status) <= 0) {
                    $bpdeviceid = $bpdeviceid;
                    $data = array('userid' => $bpuserid, 'device_id' => $bpdeviceid, 'subscription_option' => $bpsubscribeoptions, 'web_auth' => $pnfpb_endpoint, 'web_256' => $pnfpb_options, 'ip_address' => $pnfpb_ipaddress, 'firebase_version' => 'httpv4');
                    $insertstatus = $wpdb->insert($table, $data);
                    if (!$insertstatus || $insertstatus != 0) {
                        $my_id = $wpdb->insert_id;
                        echo json_encode(array('subscriptionstatus' => 'subscribed newly', 'subscriptionoptions' => $bpsubscribeoptions));
                    } else {
                        echo json_encode(array('subscriptionstatus' => 'fail', 'subscriptionoptions' => $bpsubscribeoptions));
                    }
                    /*********************************************************************************************
                     * Automate Migrate user's subscription token from Legacy Firebase to latest
                     * Firebase httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                     **********************************************************************************************/
                    if (get_option('pnfpb_httpv1_push') === '1' && $bpsubscribeoptions !== '') {
						PNFPB_httpv1_subscription_option_update($bpsubscribeoptions,$bpdeviceid,'',$old_subscription_option);
                    } else {
                    	if (get_option('pnfpb_httpv1_push') === '1') {
							PNFPB_httpv1_default_subscription_option_update($bpdeviceid);
                    	}
					}
                } else {
                    echo json_encode(array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $bpsubscribeoptions));
                }
            }
        } else {
            if ($bpuserid !== 0) {
                $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE userid = %d", $bpsubscribeoptions, $bpuserid));
            } else {
                $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE device_id LIKE %s AND device_id NOT LIKE ", $bpsubscribeoptions, '%' . $wpdb->esc_like($bpdeviceid) . '%', '%' . $wpdb->esc_like('!!') . '%'));
                $deviceid_group_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE device_id LIKE %s AND device_id LIKE %s", $bpsubscribeoptions, '%' . $wpdb->esc_like($bpdeviceid) . '%', '%' . $wpdb->esc_like('!!') . '%'));
            }
            $deviceid_select_status = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE device_id LIKE %s", '%' . $wpdb->esc_like($bpdeviceid) . '%'));
            if ($deviceid_update_status > 0) {
                $version_values = $wpdb->get_col($wpdb->prepare("SELECT firebase_version FROM {$table} WHERE device_id LIKE %s", '%' . $wpdb->esc_like($bpdeviceid) . '%'));
                $version_value = 'L';
                foreach ($version_values as $value) {
                    $version_value = $value;
                }
                /*********************************************************************************************
                 * Automate Migrate user's subscription token from Legacy Firebase to latest Firebase
                 * httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                 **********************************************************************************************/
                if (get_option('pnfpb_httpv1_push') === '1' && $bpsubscribeoptions !== '') {
					PNFPB_httpv1_subscription_option_update($bpsubscribeoptions,$bpdeviceid,'',$old_subscription_option);
                }
                $subscription_option_array = array();
                if ($bpsubscribeoptions != '') {
                    $subscription_option_array = str_split($bpsubscriptionoptions);
                }
                if (($version_value !== 'httpv3' && $version_value !== 'httpv4') && get_option('pnfpb_httpv1_push') === '1' && (count($subscription_option_array) <= '0' || (count($subscription_option_array) > 0 && $subscription_option_array[0] === '1'))) {
					PNFPB_httpv1_default_subscription_option_update($bpdeviceid);
                }
                echo json_encode(array('subscriptionstatus' => 'subscribed webview', 'subscriptionoptions' => $bpsubscribeoptions));
            }
        }
    } else {
        /*********************************************************************************************
         * Check User's Push notification subscription details in WordPress PNFPB plugin table
         * pnfpb_ic_subscribed_deviceids_web
         **********************************************************************************************/
        if ($pushtype == 'checkdeviceid') {
            $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
            $dbname = $wpdb->dbname;
            if ($bpdeviceid !== '') {
                $deviceid_select_status = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE device_id LIKE %s", '%' . $wpdb->esc_like($bpdeviceid) . '%'));
                $subscribed = true;
                foreach ($deviceid_select_status as $result) {
                    if ($result->userid == 0 || $result->userid != $bpuserid) {
                        $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET userid = %d WHERE device_id = %s", $bpuserid, $bpdeviceid));
                    }
                    if (is_null($result->web_auth)) {
                        $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET web_auth = %s,web_256 = %s,ip_address = %s WHERE device_id = %s", $pnfpb_endpoint, $pnfpb_options, $pnfpb_ipaddress, $bpdeviceid));
                    }
                    $subscriptionoptions = $result->subscription_option;
                    if ($subscriptionoptions === '10000' || $subscriptionoptions === '' || $subscriptionoptions === NULL || $subscriptionoptions === null || $subscriptionoptions === 'NULL') {
                        $subscriptionoptions = '100000000000';
                        $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE device_id = %s", $subscriptionoptions, $bpdeviceid));
                    }
                    if (strpos($result->device_id, '@N') !== false || $subscriptionoptions === '000000000000' || $subscriptionoptions === '000000000010') {
                        $subscribed = false;
                    }
                }
            } else {
                $subscriptionoptions = '000000000000';
                if (($bpdeviceid === '' || $bpsubscribeoptions === '000000000000' || $bpsubscribeoptions === '') && $bpuserid != 0) {
                    $deviceid_select_status = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE userid = %d", $bpuserid));
                    foreach ($deviceid_select_status as $result) {
                        $subscriptionoptions = $result->subscription_option;
                    }
                }
            }
            if ($deviceid_select_status != null && count($deviceid_select_status) > 0) {
                if ($subscribed) {
                    $version_values = $wpdb->get_col($wpdb->prepare("SELECT firebase_version FROM {$table} WHERE device_id = %s  AND (device_id NOT LIKE %s OR device_id LIKE %s)", $bpdeviceid, '%!!%', '%webview%'));
                    $version_value = 'L';
                    foreach ($version_values as $value) {
                        $version_value = $value;
                    }
                    /*********************************************************************************************
                     * Automate Migrate user's subscription token from Legacy Firebase to latest Firebase
                     * httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                     **********************************************************************************************/
					$bpsubscriptionoptions = $subscriptionoptions;
                    if (($version_value !== 'httpv4') && get_option('pnfpb_httpv1_push') === '1' && $subscriptionoptions !== '' && (get_option('pnfpb_custom_prompt_options_on_off') === '1' || get_option('pnfpb_bell_icon_prompt_options_on_off') === '1' || get_option('pnfpb_ic_fcm_frontend_enable_subscription') === '1' || get_option('pnfpb_shortcode_enable') === 'yes')) {
                        PNFPB_httpv1_subscription_option_update($bpsubscribeoptions,$bpdeviceid,'checkdeviceid');
                    }
                    $subscription_option_array = array();
                    if ($subscriptionoptions != '') {
                        $subscription_option_array = str_split($subscriptionoptions);
                    }
                    if (($version_value !== 'httpv4') && get_option('pnfpb_httpv1_push') === '1' && (count($subscription_option_array) <= '0' || (count($subscription_option_array) > 0 && $subscription_option_array[0] === '1'))) {
                        PNFPB_httpv1_default_subscription_option_update($bpdeviceid);
                    }
                    echo json_encode(array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $subscriptionoptions));
                } else {
                    echo json_encode(array('subscriptionstatus' => 'not-subscribed', 'subscriptionoptions' => $subscriptionoptions));
                }
            } else {
                if ($bpdeviceid !== '') {
                    $data = array('userid' => $bpuserid, 'device_id' => $bpdeviceid, 'subscription_option' => '100000000000', 'web_auth' => $pnfpb_endpoint, 'web_256' => $pnfpb_options, 'ip_address' => $pnfpb_ipaddress, 'firebase_version' => 'httpv4');
                    $insertstatus = $wpdb->insert($table, $data);
                    if (!$insertstatus || $insertstatus != 0) {
                        $my_id = $wpdb->insert_id;
                        echo json_encode(array('subscriptionstatus' => 'subscribed', 'subscriptionoptions' => $bpsubscribeoptions));
                    } else {
                        echo json_encode(array('subscriptionstatus' => 'not-subscribed', 'subscriptionoptions' => $bpsubscribeoptions));
                    }
                    /*********************************************************************************************
                     * Automate Migrate user's subscription token from Legacy Firebase to latest Firebase httpv1
                     * api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                     **********************************************************************************************/
                    if (get_option('pnfpb_httpv1_push') === '1') {
                        PNFPB_httpv1_default_subscription_option_update($bpdeviceid);
                    }
                }
            }
        } else {
            /*********************************************************************************************
             * Check User's Push notification subscription details for BuddyPress group in WordPress PNFPB
             * plugin table pnfpb_ic_subscribed_deviceids_web
             **********************************************************************************************/
            if ($bpdeviceid != '' && $pushtype == 'checkdeviceidforgroup') {
                $bpgroupid = sanitize_text_field($_POST['bpgroup_id']);
                $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
                $deviceid_select_status = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE device_id = %s AND userid = %d", $bpdeviceid . '!!' . $bpgroupid, $bpuserid));
                $subscribed = true;
                $subscriptionoptions = '000000000000';
                if (count($deviceid_select_status) > 0) {
                    $version_value = 'L';
                    foreach ($deviceid_select_status as $result) {
                        $version_value = $result->firebase_version;
                        $subscriptionoptions = $result->subscription_option;
                        if ($subscriptionoptions === '10000' || $subscriptionoptions === '' || $subscriptionoptions === NULL || $subscriptionoptions === null || $subscriptionoptions === 'NULL') {
                            $subscriptionoptions = '100000000000';
                            $deviceid_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET subscription_option = %s WHERE device_id = %s", $subscriptionoptions, $bpdeviceid));
                        }
                        /*********************************************************************************************
                         * Automate Migrate user's subscription token from Legacy Firebase to latest Firebase
                         * httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                         **********************************************************************************************/
                        if (($version_value !== 'httpv3' && $version_value !== 'httpv4') && get_option('pnfpb_httpv1_push') === '1') {
                            $group_name = groups_get_slug($bpgroupid);
                            $client = new Google_Client();
                            // Authentication with the GOOGLE_APPLICATION_CREDENTIALS environment variable
                            $client->useApplicationDefaultCredentials();
                            // Alternatively, provide the JSON authentication file directly.
                            $configArray = json_decode(get_option('pnfpb_sa_json_data'), true);
                            $client->setAuthConfig($configArray);
                            // Add the scope as a string (multiple scopes can be provided as an array)
                            $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
                            $client->refreshTokenWithAssertion();
                            $pnfpb_fbauth_token_array = $client->getAccessToken();
                            $pnfpb_fbauth_token = $pnfpb_fbauth_token_array['access_token'];
                            $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
                            $headers = array('Authorization' => 'Bearer ' . $pnfpb_fbauth_token, 'Content-Type' => 'application/json', 'access_token_auth' => 'true');
                            $grouptopic = "/topics/" . $group_name;
                            $fields = array("to" => $grouptopic, "registration_tokens" => array($bpdeviceid));
                            $body = json_encode($fields);
                            $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
                            $apiresults = wp_remote_post($url, $args);
                            $deviceid_version_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET firebase_version = %s WHERE device_id = %s", 'httpv3', $bpdeviceid));
                        }
                    }
                    echo "subscribed";
                } else {
                    echo "not-subscribed";
                }
            } else {
                /*********************************************************************************************
                 * Update User's BuddyPress group Push notification subscription details in WordPress
                 * PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                 **********************************************************************************************/
                if ($bpdeviceid != '' && $pushtype == 'subscribe-group-button') {
                    $bpgroupid = sanitize_text_field($_POST['bpgroup_id']);
                    $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
                    $dbname = $wpdb->dbname;
                    $cookievalue = '';
                    if (isset($_COOKIE['pnfpb_group_push_notification_' . $bpgroupid])) {
                        $cookievalue = $_COOKIE['pnfpb_group_push_notification_' . $bpgroupid];
                    }
                    $bpnewdeviceid = $bpdeviceid . '!!' . $bpgroupid . '!!' . $cookievalue;
                    $deviceid_select_status = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE device_id LIKE %s", '%' . $wpdb->esc_like($bpdeviceid) . '%'));
                    $subscribed = true;
                    $subscriptionoptions = '000000000000';
                    foreach ($deviceid_select_status as $result) {
                        $subscriptionoptions = $result->subscription_option;
                    }
                    $uniqueid = uniqid();
                    setcookie('pnfpb_group_push_notification_' . $bpgroupid, $uniqueid, time() + (86400 * 30), "/"); // 86400 = 1 day
                    $bpnewdeviceid = $bpdeviceid . '!!' . $bpgroupid . '!!' . $uniqueid;
                    $data = array('userid' => $bpuserid, 'device_id' => $bpnewdeviceid, 'subscription_option' => $subscriptionoptions, 'web_auth' => $pnfpb_endpoint, 'web_256' => $pnfpb_options, 'ip_address' => $pnfpb_ipaddress, 'firebase_version' => 'httpv3');
                    $insertstatus = $wpdb->insert($table, $data);
                    if (!$insertstatus || $insertstatus != 0) {
                        $my_id = $wpdb->insert_id;
                        echo 'subscribed';
                    } else {
                        echo json_encode(array('subscriptionstatus' => 'deleted'));
                    }
                    /*********************************************************************************************
                     * Automate Migrate user's subscription token from Legacy Firebase to latest
                     * Firebase httpv1 api version in WordPress PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                     **********************************************************************************************/
                    if (get_option('pnfpb_httpv1_push') === '1') {
                        $group_name = 'pnfpbgroupid' . $bpgroupid;
                        $client = new Google_Client();
                        // Authentication with the GOOGLE_APPLICATION_CREDENTIALS environment variable
                        $client->useApplicationDefaultCredentials();
                        // Alternatively, provide the JSON authentication file directly.
                        $configArray = json_decode(get_option('pnfpb_sa_json_data'), true);
                        $client->setAuthConfig($configArray);
                        // Add the scope as a string (multiple scopes can be provided as an array)
                        $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
                        $client->refreshTokenWithAssertion();
                        $pnfpb_fbauth_token_array = $client->getAccessToken();
                        $pnfpb_fbauth_token = $pnfpb_fbauth_token_array['access_token'];
                        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
                        $headers = array('Authorization' => 'Bearer ' . $pnfpb_fbauth_token, 'Content-Type' => 'application/json', 'access_token_auth' => 'true');
                        $grouptopic = "/topics/" . $group_name;
                        $fields = array("to" => $grouptopic, "registration_tokens" => array($bpdeviceid));
                        $body = json_encode($fields);
                        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
                        $apiresults = wp_remote_post($url, $args);
                    }
                } else {
                    /*********************************************************************************************
                     * Un-subscribe group push notification in PNFPB plugin table pnfpb_ic_subscribed_deviceids_web
                     **********************************************************************************************/
                    if ($bpdeviceid != '' && $pushtype == 'unsubscribe-group-button') {
                        $bpgroupid = sanitize_text_field($_POST['bpgroup_id']);
                        $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
                        $cookievalue = '';
                        if (isset($_COOKIE['pnfpb_group_push_notification_' . $bpgroupid])) {
                            $cookievalue = $_COOKIE['pnfpb_group_push_notification_' . $bpgroupid];
                        }
                        $bpolddeviceid = $bpdeviceid . '!!' . $bpgroupid . '!!' . $cookievalue;
                        $deviceid_update_status = $wpdb->query($wpdb->prepare("DELETE from {$table} WHERE userid = %d AND device_id = %s", $bpuserid, $bpolddeviceid));
                        $group_name = 'pnfpbgroupid' . $bpgroupid;
                        /*********************************************************************************************
                         * Automate Migrate user's subscription token from Legacy Firebase to latest
                         * Firebase httpv1 api version in WordPress PNFPB plugin table  pnfpb_ic_subscribed_deviceids_web
                         **********************************************************************************************/
                        if (get_option('pnfpb_httpv1_push') === '1') {
                            $client = new Google_Client();
                            // Authentication with the GOOGLE_APPLICATION_CREDENTIALS environment variable
                            $client->useApplicationDefaultCredentials();
                            // Alternatively, provide the JSON authentication file directly.
                            $configArray = json_decode(get_option('pnfpb_sa_json_data'), true);
                            $client->setAuthConfig($configArray);
                            // Add the scope as a string (multiple scopes can be provided as an array)
                            $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
                            $client->refreshTokenWithAssertion();
                            $pnfpb_fbauth_token_array = $client->getAccessToken();
                            $pnfpb_fbauth_token = $pnfpb_fbauth_token_array['access_token'];
                            $url = 'https://iid.googleapis.com/iid/v1:batchRemove';
                            $headers = array('Authorization' => 'Bearer ' . $pnfpb_fbauth_token, 'Content-Type' => 'application/json', 'access_token_auth' => 'true');
                            $grouptopic = "/topics/" . $group_name;
                            $fields = array("to" => $grouptopic, "registration_tokens" => array($bpdeviceid));
                            $body = json_encode($fields);
                            $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
                            $apiresults = wp_remote_post($url, $args);
                        }
                        if ($deviceid_update_status > 0) {
                            echo json_encode(array('subscriptionstatus' => 'deleted'));
                        } else {
                            echo json_encode(array('subscriptionstatus' => 'failed in unsubscribe button'));
                        }
                    } else {
                        /*********************************************************************************************
                         * Delete user's Push notification token in WordPress PNFPB plugin table
                         * pnfpb_ic_subscribed_deviceids_web
                         **********************************************************************************************/
                        if ($bpdeviceid != '' && $pushtype == 'deletepushtoken') {
                            $table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
                            $deviceid_update_status = $wpdb->query($wpdb->prepare("DELETE from {$table} WHERE device_id = %s", $bpdeviceid));
                            if ($deviceid_update_status > 0) {
                                echo json_encode(array('subscriptionstatus' => 'deleted', 'deviceidupdatestauts' => $deviceid_update_status, 'deviceid' => $bpdeviceid));
                            } else {
                                echo json_encode(array('subscriptionstatus' => 'failed in deleting push token', 'deviceidupdatestauts' => $deviceid_update_status, 'deviceid' => $bpdeviceid));
                            }
                        } else {
                            if ($pushtype !== 'icfirebasecred' && $pushtype !== 'onesignal_subscribed_users' && $pushtype !== 'onesignal_frontend_subscriptions' && $pushtype !== 'onesignal_get_frontend_subscriptions' && $pushtype !== 'webtoapp_subscribed_users' && $pushtype !== 'progressier_subscribed_users' && $pushtype !== 'progressier_frontend_subscriptions' && $pushtype !== 'progressier_get_frontend_subscriptions') {
                                echo json_encode(array('subscriptionstatus' => 'failed'));
                            }
                        }
                    }
                }
            }
        }
    }
}

function PNFPB_httpv1_subscription_option_update($bpsubscribeoptions,$bpdeviceid,$pushtype='',$old_subscription_option='') {
	
	/*** Function to opt for various Firebase httpv1 push notification options  ***/
	
	global $wpdb;
	$table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
	$subscription_option_array = str_split($bpsubscribeoptions);
	$old_subscription_option_array = str_split($old_subscription_option);

    $client = new Google_Client();
    // Authentication with the GOOGLE_APPLICATION_CREDENTIALS environment variable
    $client->useApplicationDefaultCredentials();
    // Alternatively, provide the JSON authentication file directly.
    $configArray = json_decode(get_option('pnfpb_sa_json_data'), true);
    $client->setAuthConfig($configArray);
    // Add the scope as a string (multiple scopes can be provided as an array)
    $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
    $client->refreshTokenWithAssertion();
    $pnfpb_fbauth_token_array = $client->getAccessToken();
    $pnfpb_fbauth_token = $pnfpb_fbauth_token_array['access_token'];
    $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
    $headers = array('Authorization' => 'Bearer ' . $pnfpb_fbauth_token, 'Content-Type' => 'application/json', 'access_token_auth' => 'true');
	
    //if (count($subscription_option_array) > 0 && $subscription_option_array[0] !== '1' ) {	
    	/*** On demand Firebase httpv1 push notification subscription group **/
		$url = 'https://iid.googleapis.com/iid/v1:batchAdd';
    	$fields = array("to" => "/topics/pnfpbondemand", "registration_tokens" => array($bpdeviceid));
    	$body = json_encode($fields);
    	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
    	$apiresults = wp_remote_post($url, $args);


	/*** Subscribe all options for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 0 && $subscription_option_array[0] === '1' && ((count($old_subscription_option_array) > 0 && $subscription_option_array[0] !== $old_subscription_option_array[0]) || count($old_subscription_option_array) <= 0 ) ) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbgeneral", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 0 && $subscription_option_array[0] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 0 && $subscription_option_array[0] !== $old_subscription_option_array[0]) || count($old_subscription_option_array) <= 0 )) {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbgeneral", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
       		$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** WordPress post subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 1 && $subscription_option_array[1] === '1' && ((count($old_subscription_option_array) > 1 && $subscription_option_array[1] !== $old_subscription_option_array[1]) || count($old_subscription_option_array) <= 1 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbpost", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 2 && $subscription_option_array[2] === '0' && $pushtype !== 'checkdeviceid') {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbpost", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
       		$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** BuddyPress Activities subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 11 && $subscription_option_array[11] === '1' && ((count($old_subscription_option_array) > 11 && $subscription_option_array[11] !== $old_subscription_option_array[11]) || count($old_subscription_option_array) <= 11 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbactivity", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 11 && $subscription_option_array[11] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 11 && $subscription_option_array[11] !== $old_subscription_option_array[11]) || count($old_subscription_option_array) <= 11 )) {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
       		$fields = array("to" => "/topics/pnfpbactivity", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** BuddyPress comments subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 2 && $subscription_option_array[2] === '1' && ((count($old_subscription_option_array) > 2 && $subscription_option_array[2] !== $old_subscription_option_array[2]) || count($old_subscription_option_array) <= 2 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbcomments", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 2 && $subscription_option_array[2] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 2 && $subscription_option_array[2] !== $old_subscription_option_array[2]) || count($old_subscription_option_array) <= 2 )) {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbcomments", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** BuddyPress Mycomments subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 3 && $subscription_option_array[3] === '1' && ((count($old_subscription_option_array) > 3 && $subscription_option_array[3] !== $old_subscription_option_array[3]) || count($old_subscription_option_array) <= 3 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbmycomments", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 3 && $subscription_option_array[3] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 3 && $subscription_option_array[3] !== $old_subscription_option_array[3]) || count($old_subscription_option_array) <= 3 )) {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbmycomments", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** New member joined subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 4 && $subscription_option_array[4] === '1' && ((count($old_subscription_option_array) > 4 && $subscription_option_array[4] !== $old_subscription_option_array[4]) || count($old_subscription_option_array) <= 4 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbnewmemberjoined", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 4 && $subscription_option_array[4] === '0' && $pushtype !== 'checkdeviceid') {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbnewmemberjoined", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** Unsubscribe Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 8 && ($subscription_option_array[8] === '1' || ($subscription_option_array[0] === '0' && $subscription_option_array[1] === '0' && $subscription_option_array[2] === '0' && $subscription_option_array[3] === '0' && $subscription_option_array[4] === '0' && $subscription_option_array[9] === '0' && $subscription_option_array[10] === '0' && $subscription_option_array[11] === '0' && $subscription_option_array[12] === '0' && $subscription_option_array[13] === '0'))) {
		
        $url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        $fields = array("to" => "/topics/pnfpbgeneral", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbpost", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbactivity", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbnewmemberjoined", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbcomments", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbmycomments", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbavatarchange", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbcoverimagechange", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbgroupdetailsupdate", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
        $fields = array("to" => "/topics/pnfpbgroupinvite", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    }
	
	/*** Avatar change subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 9 && $subscription_option_array[9] === '1' && ((count($old_subscription_option_array) > 9 && $subscription_option_array[9] !== $old_subscription_option_array[9]) || count($old_subscription_option_array) <= 9 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbavatarchange", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 9 && $subscription_option_array[9] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 9 && $subscription_option_array[9] !== $old_subscription_option_array[9]) || count($old_subscription_option_array) <= 9 )) {
       		$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbavatarchange", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** Cover image change subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 10 && $subscription_option_array[10] === '1' && ((count($old_subscription_option_array) > 10 && $subscription_option_array[10] !== $old_subscription_option_array[10]) || count($old_subscription_option_array) <= 10 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbcoverimagechange", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 10 && $subscription_option_array[10] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 10 && $subscription_option_array[10] !== $old_subscription_option_array[10]) || count($old_subscription_option_array) <= 10 )) {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbcoverimagechange", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** Group invite subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 12 && $subscription_option_array[12] === '1' && ((count($old_subscription_option_array) > 12 && $subscription_option_array[12] !== $old_subscription_option_array[12]) || count($old_subscription_option_array) <= 12 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbgroupinvite", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 12 && $subscription_option_array[12] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 12 && $subscription_option_array[12] !== $old_subscription_option_array[12]) || count($old_subscription_option_array) <= 12 )) {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbgroupinvite", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	/*** Group details update subscription for Firebase httpv1 push notification  ***/
	
    if (count($subscription_option_array) > 13 && $subscription_option_array[13] === '1' && ((count($old_subscription_option_array) > 13 && $subscription_option_array[13] !== $old_subscription_option_array[13]) || count($old_subscription_option_array) <= 13 )) {
        $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        $fields = array("to" => "/topics/pnfpbgroupdetailsupdate", "registration_tokens" => array($bpdeviceid));
        $body = json_encode($fields);
        $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        $apiresults = wp_remote_post($url, $args);
    } else {
		if (count($subscription_option_array) > 13 && $subscription_option_array[13] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > 13 && $subscription_option_array[13] !== $old_subscription_option_array[13]) || count($old_subscription_option_array) <= 13 )) {
        	$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        	$fields = array("to" => "/topics/pnfpbgroupdetailsupdate", "registration_tokens" => array($bpdeviceid));
        	$body = json_encode($fields);
        	$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        	$apiresults = wp_remote_post($url, $args);
		}
    }
	
	$args = array(
		'public'   => true,
		'_builtin' => false
	); 
	
	/*** Custom post types subscription for Firebase httpv1 push notification  ***/
	
	$output = 'names'; // or objects
	$operator = 'and'; // 'and' or 'or'
	$custposttypes = get_post_types( $args, $output, $operator );
							
	$custom_post_type_max_index = 6;
	
	$custom_post_type_index = 1;
							
	$custom_post_type_increment = 14;
	
	/*** Maximum 5 custom post types can be opted for Firebase httpv1 push notification  ***/
							
	foreach ( $custposttypes as $post_type ) {
		
		if (get_option('pnfpb_ic_fcm_'.$post_type.'_enable') === '1' && $post_type !== 'buddypress' && $post_type !== 'post' && ($custom_post_type_max_index >= $custom_post_type_index)) {
			
			$pnfpb_custom_post_type_groupname = "/topics/pnfpb".$post_type;
			
    		if (count($subscription_option_array) > $custom_post_type_increment && $subscription_option_array[$custom_post_type_increment] === '1' && ((count($old_subscription_option_array) > $custom_post_type_increment && $subscription_option_array[$custom_post_type_increment] !== $old_subscription_option_array[$custom_post_type_increment]) || count($old_subscription_option_array) <= $custom_post_type_increment )) {
       			$url = 'https://iid.googleapis.com/iid/v1:batchAdd';
        		$fields = array("to" => $pnfpb_custom_post_type_groupname, "registration_tokens" => array($bpdeviceid));
        		$body = json_encode($fields);
        		$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        		$apiresults = wp_remote_post($url, $args);
    		} else {
				if (count($subscription_option_array) > $custom_post_type_increment && $subscription_option_array[$custom_post_type_increment] === '0' && $pushtype !== 'checkdeviceid' && ((count($old_subscription_option_array) > $custom_post_type_increment && $subscription_option_array[$custom_post_type_increment] !== $old_subscription_option_array[$custom_post_type_increment]) || count($old_subscription_option_array) <= $custom_post_type_increment )) {
        			$url = 'https://iid.googleapis.com/iid/v1:batchRemove';
        			$fields = array("to" => $pnfpb_custom_post_type_groupname, "registration_tokens" => array($bpdeviceid));
        			$body = json_encode($fields);
        			$args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
        			$apiresults = wp_remote_post($url, $args);
				}
    		}
			
		}
		$custom_post_type_increment++;
		$custom_post_type_index++;
		
	}
	
    $deviceid_version_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET firebase_version = %s WHERE device_id = %s", 'httpv4', $bpdeviceid));
	
}

function PNFPB_httpv1_default_subscription_option_update($bpdeviceid) {
	
	/*** Function to opt for default Firebase httpv1 push notification for all options  ***/
	
	global $wpdb;
	$table = $wpdb->prefix . 'pnfpb_ic_subscribed_deviceids_web';
    $client = new Google_Client();
    // Authentication with the GOOGLE_APPLICATION_CREDENTIALS environment variable
    $client->useApplicationDefaultCredentials();
    // Alternatively, provide the JSON authentication file directly.
    $configArray = json_decode(get_option('pnfpb_sa_json_data'), true);
    $client->setAuthConfig($configArray);
    // Add the scope as a string (multiple scopes can be provided as an array)
    $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
    $client->refreshTokenWithAssertion();
    $pnfpb_fbauth_token_array = $client->getAccessToken();
    $pnfpb_fbauth_token = $pnfpb_fbauth_token_array['access_token'];
    $url = 'https://iid.googleapis.com/iid/v1:batchAdd';
    $headers = array('Authorization' => 'Bearer ' . $pnfpb_fbauth_token, 'Content-Type' => 'application/json', 'access_token_auth' => 'true');
	
    if (get_option('pnfpb_ic_fcm_loggedin_notify') && get_option('pnfpb_ic_fcm_loggedin_notify') === '1') {
        $fields = array("to" => "/topics/pnfpbgeneralloggedin", "registration_tokens" => array($bpdeviceid));
    } else {
        $fields = array("to" => "/topics/pnfpbgeneral", "registration_tokens" => array($bpdeviceid));
    }
	
    $body = json_encode($fields);
    $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
    $apiresults = wp_remote_post($url, $args);
	
    /*** On demand Firebase httpv1 push notification subscription group **/
	$url = 'https://iid.googleapis.com/iid/v1:batchAdd';
    $fields = array("to" => "/topics/pnfpbondemand", "registration_tokens" => array($bpdeviceid));
    $body = json_encode($fields);
    $args = array('httpversion' => '1.0', 'blocking' => true, 'sslverify' => false, 'body' => $body, 'headers' => $headers);
    $apiresults = wp_remote_post($url, $args);
	
    $deviceid_version_update_status = $wpdb->query($wpdb->prepare("UPDATE {$table} SET firebase_version = %s WHERE device_id = %s", 'httpv4', $bpdeviceid));	
}

wp_die();
?>