<?php

			$register_settings_args = array(
    				'sanitize_callback' => 'sanitize_text_field'
   				);
			
			$register_settings_args_for_url = array(
				'type'              => 'string',
				'sanitize_callback' => 'esc_url_raw',
				'default'           => '',
			);
            //register our settings
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_google_api",$register_settings_args);
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_api",$register_settings_args);
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_authdomain",$register_settings_args);
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_databaseurl",$register_settings_args_for_url);
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_projectid",$register_settings_args);
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_storagebucket",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_group_config",
                "pnfpb_ic_fcm_messagingsenderid",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_appid",$register_settings_args);
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_publickey",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_activity_title",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_activity_message",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_group_activity_title",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_group_activity_message",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_comment_activity_title",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_comment_activity_message",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_group_config", "pnfpb_ic_fcm_upload_icon",$register_settings_args_for_url);
            register_setting("pnfpb_icfcm_group_config", "pnfpb_onesignal_push",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_group_config",
                "pnfpb_ic_fcm_progressier_api_key",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_group_config", "pnfpb_progressier_push",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_group_config",
                "pnfpb_ic_fcm_webtoapp_api_key",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_group_config", "pnfpb_webtoapp_push", $register_settings_args);
			register_setting("pnfpb_icfcm_group_config", "pnfpb_webpush_push", $register_settings_args);
			register_setting("pnfpb_icfcm_group_config", "pnfpb_webpush_push_firebase", $register_settings_args);
			register_setting("pnfpb_icfcm_group_config", "pnfpb_webpush_firebase_public_key", $register_settings_args);
			register_setting("pnfpb_icfcm_group_config", "pnfpb_webpush_firebase_private_key", $register_settings_args);
            register_setting("pnfpb_icfcm_group", "pnfpb_ic_fcm_prompt_style",$register_settings_args);
            register_setting("pnfpb_icfcm_group", "pnfpb_ic_fcm_prompt_on_off",$register_settings_args);
            register_setting("pnfpb_icfcm_group", "pnfpb_ic_fcm_prompt_style3",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_update_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_update_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_update_background_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_update_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_list_background_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_list_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_list_checkbox_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_update_confirmation_message",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_all_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_post_text",
				$register_settings_args
            );

            $args = [
                "public" => true,
                "_builtin" => false,
            ];

            $output = "names"; // or objects

            $operator = "and"; // 'and' or 'or'

            $custposttypes = get_post_types($args, $output, $operator);

            foreach ($custposttypes as $post_type) {
                register_setting(
                    "pnfpb_icfcm_group",
                    "pnfpb_bell_icon_subscription_option_" .
                        $post_type .
                        "_text",
					$register_settings_args
                );
            }

            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_activity_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_all_comments_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_my_comments_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_private_message_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_new_member_joined_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_friendship_request_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_friendship_accepted_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_avatar_change_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_cover_image_change_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_group_details_update_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_group_invite_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_subscription_option_favourite_text",
				$register_settings_args
            );			
			
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_label_text_shortcode",
				$register_settings_args
            );	
			
            register_setting(
                "pnfpb_icfcm_buttons",			
				"pnfpb_ic_fcm_bellicon_shortcode_style",
				$register_settings_args
			);
			
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_all_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_post_text_shortcode",
				$register_settings_args
            );

            $args = [
                "public" => true,
                "_builtin" => false,
            ];

            $output = "names"; // or objects

            $operator = "and"; // 'and' or 'or'

            $custposttypes = get_post_types($args, $output, $operator);

            foreach ($custposttypes as $post_type) {
                register_setting(
                    "pnfpb_icfcm_buttons",
                    "pnfpb_bell_icon_subscription_option_" .
                        $post_type .
                        "_text_shortcode",
					$register_settings_args
                );
            }

            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_activity_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_all_comments_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_my_comments_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_private_message_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_new_member_joined_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_friend_request_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_friendship_accepted_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_user_avatar_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_cover_image_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_group_details_update_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_group_invite_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_subscription_option_favourite_text_shortcode",
				$register_settings_args
            );			
			
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_custom_prompt_subscribe_button_icon",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_animation",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_header_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_header_text_line_2",
				$register_settings_args
            );			
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_subscribed_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_custom_prompt_confirmation_message_on_off",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_show_again_days",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_allow_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_custom_prompt_allow_button_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_allow_button_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_cancel_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_custom_prompt_cancel_button_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_cancel_button_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_close_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_custom_prompt_close_button_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_close_button_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_confirm_button",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_cancel_button",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_button_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_dialog_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_push_prompt_position",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_custom_prompt_popup_wait_message",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_custom_prompt_options_on_off",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_bell_icon_prompt_options_on_off",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_bell_icon_prompt_options_on_off_shortcode",
				$register_settings_args
            );			
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_loggedin_notify",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_turnoff_foreground_messages",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_renotify_notification",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_async_notifications",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_replace_notifications",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_show_allposttype_subscriptions_custom_prompt",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_group", "pnfpb_ic_fcm_post_enable",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_only_post_subscribers_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_disable_post_update_enable",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_group", "pnfpb_ic_fcm_post_title",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_bcomment_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_bactivity_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_bprivatemessage_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_bprivatemessage_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_bprivatemessage_content",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_new_member_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_new_member_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_new_member_content",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_friendship_request_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_friendship_request_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_friendship_request_content",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_friendship_accept_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_friendship_accept_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_friendship_accept_content",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_mark_favourite_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_mark_favourite_text_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_mark_favourite_content_enable",
				$register_settings_args
            );			
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_avatar_change_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_avatar_change_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_avatar_change_content",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_cover_image_change_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_cover_image_change_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_cover_image_change_content",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_group_invitation_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_group_invitation_text_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_group_invitation_content_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_group_details_updated_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_group_details_updated_text_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_group_details_updated_content_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_contact_form7_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_contact_form7_text_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_contact_form7_content_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_new_user_registration_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_new_user_registration_text_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_new_user_registration_content_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_post_schedule_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_post_schedule_background_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_post_schedule_now_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_activity_schedule_now_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_comments_schedule_now_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypressoptions_schedule_now_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_admin_schedule_now_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_post_timeschedule_seconds",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypressactivities_schedule_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypressactivities_schedule_background_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypressactivities_timeschedule_seconds",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_followers_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypresscomments_schedule_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypress_comments_radio_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypresscomments_schedule_background_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypresscomments_timeschedule_seconds",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_subscribe_button_icon",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_subscribe_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_subscribe_button_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_subscribe_button",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_unsubscribe_button",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_header_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_subscribe_message",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_unsubscribe_message",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_popup_wait_message",
				$register_settings_args
            );
			
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_shortcode_installed",
				$register_settings_args
            );

            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_subscribe_button_icon_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_subscribe_button_text_color_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_subscribe_button_color_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_subscribe_button_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_unsubscribe_button_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_header_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_subscribe_message_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_unsubscribe_message_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_popup_wait_message_shortcode",
				$register_settings_args
            );
			
            $pnfpb_pwa_args = [
                "type" => "array",
				"sanitize_callback" => [
					$this,
					"pnfpb_ic_fcm_santize_array_callback",
				],				
            ];			

            register_setting("pnfpb_icfcm_group_config", "pnfpb_httpv1_push",$register_settings_args);

            register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_enable",$register_settings_args);
            register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_name",$register_settings_args);
            register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_shortname",$register_settings_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_scope",$register_settings_args_for_url);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_starturl",$register_settings_args_for_url);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_orientation",$register_settings_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_description",$register_settings_args);
            register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_theme_color",$register_settings_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_shortcut_name",$pnfpb_pwa_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_shortcut_shortname",$pnfpb_pwa_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_shortcut_starturl",$pnfpb_pwa_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_shortcut_description",$pnfpb_pwa_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_fcm_pwa_shortcut_upload_icon_132",$pnfpb_pwa_args);
			register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_fcm_pwa_shortcut_upload_icon_512",$pnfpb_pwa_args);			
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_backgroundcolor",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_display",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_icon_132",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_icon_512",
				$register_settings_args_for_url
            );
            register_setting("pnfpb_icfcm_pwa", "pnfpb-pwa-ios-message",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_screenshot_desktop_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_screenshot_desktop_label",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_screenshot_mobile_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_screenshot_mobile_label",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_splashscreen_640_1136_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_splashscreen_750_1294_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_splashscreen_1242_2148_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_splashscreen_1125_2436_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_splashscreen_1536_2048_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_splashscreen_1668_2224_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_upload_splashscreen_2048_2732_value",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_thirdparty_pwa_app_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_thirdparty_app_id",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_protocol_name",
                $pnfpb_pwa_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_protocol_url",
                $pnfpb_pwa_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_offline_url1",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_offline_url2",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_offline_url3",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_offline_url4",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_offline_url5",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_excludeallurls",
				$register_settings_args
            );
            register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_pwa_app_excludeurls",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_custom_prompt_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_desktop_custom_prompt_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_mobile_custom_prompt_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_pixels_custom_prompt_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_app_pixels_input_custom_prompt_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_prompt_install_button_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_prompt_header_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_prompt_description",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_prompt_install_button_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_pwa_prompt_install_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb-pwa-dialog-app-installed_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb-pwa-dialog-app-installed_description",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_prompt_confirm_button",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_prompt_cancel_button",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_prompt_button_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_prompt_dialog_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_prompt_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_prompt_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_ios_prompt_dialog_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_ios_prompt_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_ios_prompt_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_ios_prompt_button_background",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_ios_prompt_ok_button",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_ios_pwa_prompt_disable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_ios_pwa_prompt_reappear",
				$register_settings_args
            );			
            register_setting("pnfpb_icfcm_pwa", "pnfpb_ic_fcm_pwa_prompt_text",$register_settings_args);
            register_setting(
                "pnfpb_icfcm_pwa",
                "pnfpb_ic_fcm_pwa_show_again_days",
				$register_settings_args
            );

            register_setting(
                "pnfpb_icfcm_nginx",
                "pnfpb_ic_nginx_static_files_enable",
				$register_settings_args
            );

            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_button_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_button_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_subscribe_group_push_notification_icon",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_unsubscribe_button_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_unsubscribe_group_push_notification_icon",
				$register_settings_args_for_url
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_subscribe_group_push_notification_icon_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_group_subscribe_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_group_subscribe_dialog_text_confirm",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_group_unsubscribe_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_group_unsubscribe_dialog_text_confirm",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_unsubscribe_button_shortcode_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_button_shortcode_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_save_button_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_unsubscribe_cancel_button_text_shortcode",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_shortcode_close_button_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_subheading_notoken_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_subheading_withtoken_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_all_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_post_activity_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb-pwa-shortcode-install-icon",
				$register_settings_args_for_url
            );

            $args = [
                "public" => true,
                "_builtin" => false,
            ];

            $output = "names"; // or objects

            $operator = "and"; // 'and' or 'or'

            $custposttypes = get_post_types($args, $output, $operator);

            foreach ($custposttypes as $post_type) {
                register_setting(
                    "pnfpb_icfcm_buttons",
                    "pnfpb_ic_fcm_subscribe_" . $post_type . "_dialog_text",
					$register_settings_args
                );
            }
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_all_comments_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_my_comments_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_private_message_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_new_member_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_friend_request_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_friendship_accepted_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_user_avatar_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_cover_image_change_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_unsubscribe_all_dialog_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_subscribe_dialog_text_confirm",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_unsubscribe_dialog_text_confirm",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_install_pwa_shortcode_button_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_install_pwa_shortcode_button_text_color",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_buttons",
                "pnfpb_ic_fcm_install_pwa_shortcode_button_text",
				$register_settings_args
            );

            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_enable_subscription",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_post_text",
				$register_settings_args
            );

            $args = [
                "public" => true,
                "_builtin" => false,
            ];

            $output = "names"; // or objects

            $operator = "and"; // 'and' or 'or'

            $custposttypes = get_post_types($args, $output, $operator);

            foreach ($custposttypes as $post_type) {
                register_setting(
                    "pnfpb_icfcm_frontend_buttons",
                    "pnfpb_ic_fcm_frontend_settings_" . $post_type . "_text",
					$register_settings_args
                );
            }

            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_activities_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_comments_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_mycomments_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_privatemessage_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_newmember_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_friend_request_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_friend_accept_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_avatar_change_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_coverimage_change_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_groupinvite_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_groupdetails_text",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_frontend_buttons",
                "pnfpb_ic_fcm_frontend_settings_favourite_text",
				$register_settings_args
            );			

            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_post_timeschedule_enable",
                [
                    "type" => "string",
                    "sanitize_callback" => [
                        $this,
                        "pnfpb_ic_fcm_post_timeschedule_callback",
                    ],
                ]
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypressactivities_schedule_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypressactivities_timeschedule_enable",
                [
                    "type" => "string",
                    "sanitize_callback" => [
                        $this,
                        "pnfpb_ic_fcm_buddypressactivities_timeschedule_callback",
                    ],
                ]
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypresscomments_schedule_enable",
				$register_settings_args
            );
            register_setting(
                "pnfpb_icfcm_group",
                "pnfpb_ic_fcm_buddypresscomments_timeschedule_enable",
                [
                    "type" => "string",
                    "sanitize_callback" => [
                        $this,
                        "pnfpb_ic_fcm_buddypresscomments_timeschedule_callback",
                    ],
                ]
            );

            $args = [
                "public" => true,
                "_builtin" => false,
            ];

            $output = "names"; // or objects
            $operator = "and"; // 'and' or 'or'
            $custposttypes = get_post_types($args, $output, $operator);

            foreach ($custposttypes as $post_type) {
                $fieldname = "pnfpb_ic_fcm_" . $post_type . "_enable";
                register_setting("pnfpb_icfcm_group", $fieldname,$register_settings_args);
                register_setting(
                    "pnfpb_icfcm_group",
                    "pnfpb_ic_fcm_" . $post_type . "_title",
					$register_settings_args
                );
            }


?>